// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hfakwyiyiwtspfeqtqio.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhmYWt3eWl5aXd0c3BmZXF0cWlvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mjk5NTE1NjksImV4cCI6MjA0NTUyNzU2OX0.UMPrMIJP3kMh188ry31J9z2ArbpEXPnPv5WJxFDUO5k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});